apiVersion: v1
kind: Service
metadata:
  namespace: three-tier-app-ns
  name: mongo-db-svc
spec:
  selector:
    app: mongodb
  ports:
  - name: mongo-db-svc
    protocol: TCP
    port: 27017
    targetPort: 27017
  